# build wasm-web lib
wasm-build:
    cargo install wasm-pack
    cargo install wasm-bindgen-cli
    RUSTFLAGS='--cfg getrandom_backend="wasm_js"' wasm-pack -vvv build --target web --release --out-dir web/dist
